### ISSUE TITLE
Null-safety migration

### ISSUE THREAD

**Issue by definev** [psiroki/exifdart#2]
Please migrate package.

**Comment by psiroki** [comment]
Finally I've had some time and did a null-safe prerelease, the version must be explicitly referred in your own pubspec:
```
dependencies:
  exifdart: 0.8.0-dev.1
```
It seems to be working with whatever jpg I would throw at it, but I'm not sure. I'm going to re-release it as `0.8.0` if I don't get any issues with this for like a month or two, maybe earlier.
The live project I'm using this with is still going to be using 0.7.0+2, since I can't port that project to null safety yet.
